version: 1.0.0.{build}
image: Visual Studio 2017
nuget:
  account_feed: true
  project_feed: true
clone_folder: c:\work
build_script:
  - cmd: PowerShell -Version 2.0 .\build.ps1 -Target NugetPack
artifacts:
 - path: '*.nupkg' 